# Exercise 9

## Mashable news stories analysis

Predicting if a news story is going to be popular


In [27]:
import pandas as pd
import numpy as np

url = 'https://raw.githubusercontent.com/albahnsen/PracticalMachineLearningClass/master/datasets/mashable.csv'
train_df = pd.read_csv(url, index_col=0)
train_df.head()

url  timedelta  \
0  http://mashable.com/2014/12/10/cia-torture-rep...       28.0   
1  http://mashable.com/2013/10/18/bitlock-kicksta...      447.0   
2  http://mashable.com/2013/07/24/google-glass-po...      533.0   
3  http://mashable.com/2013/11/21/these-are-the-m...      413.0   
4  http://mashable.com/2014/02/11/parking-ticket-...      331.0   

   n_tokens_title  n_tokens_content  n_unique_tokens  n_non_stop_words  \
0             9.0             188.0         0.732620               1.0   
1             7.0             297.0         0.653199               1.0   
2            11.0             181.0         0.660377               1.0   
3            12.0             781.0         0.497409               1.0   
4             8.0             177.0         0.685714               1.0   

   n_non_stop_unique_tokens  num_hrefs  num_self_hrefs  num_imgs   ...     \
0                  0.844262        5.0             1.0       1.0   ...      
1                  0.815789        9.0             4.0       1.0   ...      
2                  0.775701        4.0             3.0       1.0   ...      
3                  0.677350       10.0             3.0       1.0   ...      
4                  0.830357        3.0             2.0       1.0   ...      

   min_positive_polarity  max_positive_polarity  avg_negative_polarity  \
0               0.200000                   0.80              -0.487500   
1               0.160000                   0.50              -0.135340   
2               0.136364                   1.00               0.000000   
3               0.100000                   1.00              -0.195701   
4               0.100000                   0.55              -0.175000   

   min_negative_polarity  max_negative_polarity  title_subjectivity  \
0                  -0.60              -0.250000                 0.9   
1                  -0.40              -0.050000                 0.1   
2                   0.00               0.000000                 0.3   
3                  -0.40              -0.071429                 0.0   
4                  -0.25              -0.100000                 0.0   

   title_sentiment_polarity  abs_title_subjectivity  \
0                       0.8                     0.4   
1                      -0.1                     0.4   
2                       1.0                     0.2   
3                       0.0                     0.5   
4                       0.0                     0.5   

   abs_title_sentiment_polarity  Popular  
0                           0.8        1  
1                           0.1        0  
2                           1.0        0  
3                           0.0        0  
4                           0.0        0  

[5 rows x 61 columns]

In [5]:
train_df.shape

(6000, 61)

In [6]:
X = train_df.drop(['url', 'Popular'], axis=1)
y = train_df['Popular']

In [7]:
y.mean()

0.5

In [8]:
# train/test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

# Exercise 9.1

Estimate a Decision Tree Classifier and a Logistic Regresion

Evaluate using the following metrics:
* Accuracy
* F1-Score

In [ ]:
# Entrenar con train y validar con test

In [9]:
#from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
#from sklearn.naive_bayes import GaussianNB
#from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LogisticRegression


#          'nb': GaussianNB(),
#          'kn': KNeighborsRegressor()
models = {'logr': LogisticRegression(),
          'dt': DecisionTreeRegressor(),
         }

In [10]:
for model in models.keys():
    models[model].fit(X_train, y_train)

In [12]:
# predict test for each model
y_pred = pd.DataFrame(index=y_test.index, columns=models.keys())
for model in models.keys():
    y_pred[model] = models[model].predict(X_test)
    

In [23]:
y_pred.head()

logr   dt
1483     1  0.0
2185     1  0.0
2520     1  1.0
3721     1  0.0
3727     0  0.0

In [19]:
from sklearn import metrics
accur=[]
f1sco=[]
for i in range(y_pred.shape[1]):
    accur.append(metrics.accuracy_score(y_pred.iloc[:,i],y_test))
    f1sco.append(metrics.f1_score(y_pred.iloc[:,i], y_test))

In [34]:
accur#, columns=models.keys())  #accur

[0.6206666666666667, 0.5493333333333333]

In [22]:
f1sco

[0.6034843205574913, 0.546916890080429]

# Exercise 9.2

Estimate 300 bagged samples

Estimate the following set of classifiers:

* 100 Decision Trees where max_depth=None
* 100 Decision Trees where max_depth=2
* 100 Logistic Regressions

In [38]:
# En 100 arboles con max_depth none
#otros 100 para 2
#otras 100 logisticas
###Generar las muestras
# set a seed for reproducibility
np.random.seed(23)

n_samples = X_train.shape[0]
n_B = 100

# create ten bootstrap samples (will be used to select rows from the DataFrame)
samples = [np.random.choice(a=n_samples, size=n_samples, replace=True) for _ in range(1, n_B +1 )]
samples2 = [np.random.choice(a=n_samples, size=n_samples, replace=True) for _ in range(1, n_B +1 )]
samples3 = [np.random.choice(a=n_samples, size=n_samples, replace=True) for _ in range(1, n_B +1 )]
samples

[array([ 595, 1064, 1993, ..., 3875, 3662, 2552]),
 array([3868,  768, 3522, ..., 3377, 1863, 3196]),
 array([ 261, 2818, 3130, ..., 1084, 2464, 1900]),
 array([2922, 2213, 4322, ..., 1449, 2241,  988]),
 array([1482,  793,  375, ...,  533, 2595,  300]),
 array([2954, 3187, 3436, ..., 3442, 2631, 2595]),
 array([3232, 3528, 3472, ..., 4302, 3067, 2005]),
 array([ 871, 1643, 2169, ...,  390,  861,  240]),
 array([2357, 3296, 1652, ...,  311, 2630, 2937]),
 array([2755, 4206, 1519, ..., 4130, 3388,  125]),
 array([3565, 1509,  214, ..., 2112, 4409, 2796]),
 array([2981, 2178, 2463, ...,  910, 1636,  649]),
 array([1783,  348, 4179, ...,  771, 3831, 4354]),
 array([3972, 2236, 3890, ..., 4146, 3808,  693]),
 array([2582,  356,  808, ..., 4102, 1514, 4325]),
 array([2072, 2516,  355, ..., 2937, 2821,  603]),
 array([3867, 3216, 3672, ..., 3151, 2916, 4282]),
 array([3410, 1785, 2293, ..., 4224,  872,  588]),
 array([1264,  902,  520, ..., 2805, 1751, 3713]),
 array([3977, 4140,  232, ..., 

Generar los primeros 100 arboles con el dt y max_depth=None

In [44]:
from sklearn.tree import DecisionTreeClassifier

# grow each tree deep
treereg = DecisionTreeClassifier(max_depth=None, random_state=123)

# DataFrame for storing predicted price from each tree
y_pred = pd.DataFrame(index=X_test.index, columns=[list(range(n_B))])

# grow one tree for each bootstrap sample and make predictions on testing data
for i, sample in enumerate(samples):
    X_train_dt = X_train.iloc[sample, :]
    y_train_dt = y_train.iloc[sample]
    treereg.fit(X_train_dt, y_train_dt)
    y_pred[i] = treereg.predict(X_test)

Generar los siguientes 100 arboles con el dt y max_depth=2

In [45]:
from sklearn.tree import DecisionTreeClassifier

# grow each tree deep
treereg = DecisionTreeClassifier(max_depth=2, random_state=123)

# DataFrame for storing predicted price from each tree
y_pred = pd.DataFrame(index=X_test.index, columns=[list(range(n_B))])

# grow one tree for each bootstrap sample and make predictions on testing data
for i, sample2 in enumerate(samples):
    X_train_dt = X_train.iloc[sample2, :]
    y_train_dt = y_train.iloc[sample2]
    treereg.fit(X_train_dt, y_train_dt)
    y_pred[i] = treereg.predict(X_test)

Generar 100 regresiones logisticas

In [ ]:
from sklearn.tree import DecisionTreeClassifier

# grow each tree deep
treereg = DecisionTreeClassifier(max_depth=None, random_state=123)

# DataFrame for storing predicted price from each tree
y_pred = pd.DataFrame(index=X_test.index, columns=[list(range(n_B))])

# grow one tree for each bootstrap sample and make predictions on testing data
for i, sample3 in enumerate(samples):
    X_train_dt = X_train.iloc[sample3, :]
    y_train_dt = y_train.iloc[sample3]
    treereg.fit(X_train_dt, y_train_dt)
    y_pred[i] = treereg.predict(X_test)

# Exercise 9.3

Ensemble using majority voting

Evaluate using the following metrics:
* Accuracy
* F1-Score

# Exercise 9.4

Estimate te probability as %models that predict positive

Modify the probability threshold and select the one that maximizes the F1-Score

In [ ]:
#Estimar la probabilidad con bagging
#mover el treshhold y maximizar el f1 score
#probar aprox unos 20 y hacer la grafica

# Exercise 9.5

Ensemble using weighted voting using the oob_error

Evaluate using the following metrics:
* Accuracy
* F1-Score

In [ ]:
# Cambiar a weighted voting utilizar el oob

# Exercise 9.6

Estimate te probability of the weighted voting

Modify the probability threshold and select the one that maximizes the F1-Score

# Exercise 9.7

Estimate a logistic regression using as input the estimated classifiers

Modify the probability threshold such that maximizes the F1-Score